// Package license verifies and evaluates the on-premise licence.
//
// # DESIGN, AND WHY IT IS THIS SHAPE
//
// On-premise deployments are frequently air-gapped, so validation is entirely OFFLINE: a signed
// file, verified locally against a public key compiled into the binary. There is no phone-home in
// this package, and none should be added to it — a licence check that needs the network is a licence
// check that fails when the network does.
//
// Ed25519 rather than a bespoke scheme: verification is a few lines of standard library, and forging
// a licence requires the private key rather than merely reading how we validate. The private key
// lives only in Authnull's signing tooling.
//
// # THE RULE THAT OUTRANKS EVERYTHING ELSE IN THIS PACKAGE
//
// A licence gates the CONTROL plane. It never gates the DATA plane.
//
// This product sits in the authentication path of customers' domain controllers. If expiry failed
// closed, a billing lapse would stop authentication across a customer's domain — an outage we
// caused, on their most critical path. If it failed open, MFA would silently stop being enforced and
// they would be less secure without being told.
//
// So an expired licence makes the CONSOLE read-only and leaves enforcement untouched. The customer
// loses the ability to change their deployment, which is the commercial lever, and loses neither
// availability nor security. See pkg/license/gate.go for how that is enforced, including why the
// gated set is an explicit list rather than an exclusion list.
package license

import (
	"bytes"
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"
)

// Feature names. These exist so tiers can be sold separately, and are the only limits enforced in
// v1 — expiry plus features. Seat counting is deliberately absent: the honest enforcement for this
// product would have to be soft (a hard block partway through an AD sync is indistinguishable from
// an outage), which makes it a reporting feature rather than a licence one.
const (
	FeatureAD       = "ad"
	FeatureDatabase = "database"
	FeatureRADIUS   = "radius"
)

// Payload is the signed content of a licence. Field names are part of the file format: changing one
// invalidates every licence already issued, so add rather than rename.
type Payload struct {
	// ID identifies this licence in Authnull's records, and is what a customer quotes in support.
	ID string `json:"id"`
	// Customer is shown in the console. Display only — never an authorisation input.
	Customer string `json:"customer"`
	// IssuedAt and ExpiresAt are dates, in UTC.
	IssuedAt  time.Time `json:"issuedAt"`
	ExpiresAt time.Time `json:"expiresAt"`
	// Tier is a label for support and reporting, not a gate. Gates read Features.
	Tier string `json:"tier,omitempty"`
	// Features enables modules. An EMPTY list means no modules, not all of them: a licence that
	// fails to list what it grants should grant nothing, so a malformed or truncated file cannot
	// silently unlock the product.
	Features []string `json:"features"`
	// Nonce makes two licences issued the same second for the same customer distinguishable, so a
	// reissue can be told from a copy.
	Nonce string `json:"nonce,omitempty"`
}

// Has reports whether the licence grants a feature. Case- and space-insensitive because a licence is
// generated by tooling that a human edits.
func (p Payload) Has(feature string) bool {
	want := strings.ToLower(strings.TrimSpace(feature))
	for _, f := range p.Features {
		if strings.ToLower(strings.TrimSpace(f)) == want {
			return true
		}
	}
	return false
}

// file is the on-disk shape: the payload verbatim plus a detached signature.
//
// The payload is carried as a raw JSON string rather than a nested object, because the signature
// covers exact bytes. Re-marshalling a decoded struct can reorder keys or change number formatting,
// and the signature would then fail to verify for reasons no one could see.
type file struct {
	Payload   json.RawMessage `json:"payload"`
	Signature string          `json:"signature"` // base64 standard encoding, Ed25519 over Payload
}

var (
	// ErrNoLicense means no licence is installed. It is NOT an error condition in itself — a fresh
	// install has no licence and runs on the trial.
	ErrNoLicense = errors.New("license: none installed")
	// ErrMalformed means the file is not a licence at all.
	ErrMalformed = errors.New("license: malformed file")
	// ErrBadSignature means the signature does not verify. Distinguished from ErrMalformed because
	// this one says somebody edited a real licence.
	ErrBadSignature = errors.New("license: signature does not verify")
)

// Verify parses and cryptographically checks a licence file.
//
// It deliberately does NOT consider expiry: verification answers "did Authnull issue this, and is it
// intact", and Evaluate answers "what does it entitle you to right now". Keeping them apart means an
// expired licence can still be displayed accurately in the console — customer, dates, features —
// rather than being indistinguishable from a forgery.
func Verify(raw []byte, publicKey ed25519.PublicKey) (*Payload, error) {
	if len(raw) == 0 {
		return nil, ErrNoLicense
	}
	if len(publicKey) != ed25519.PublicKeySize {
		return nil, fmt.Errorf("license: public key is %d bytes, want %d", len(publicKey), ed25519.PublicKeySize)
	}

	var f file
	if err := json.Unmarshal(raw, &f); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrMalformed, err)
	}
	if len(f.Payload) == 0 || f.Signature == "" {
		return nil, fmt.Errorf("%w: payload or signature missing", ErrMalformed)
	}

	sig, err := base64.StdEncoding.DecodeString(f.Signature)
	if err != nil {
		return nil, fmt.Errorf("%w: signature is not base64: %v", ErrMalformed, err)
	}

	// Sign and verify over the COMPACTED payload, never the bytes as they happen to sit on disk.
	//
	// A licence is a JSON file that humans open, mail to each other and paste into tickets, and
	// plenty of tools reformat JSON on save. If the signature covered the literal file bytes, an
	// editor adding two spaces would make a genuine licence indistinguishable from a forgery — and
	// the customer would be told their file had been tampered with because they opened it.
	//
	// Compacting removes exactly the insignificant whitespace and nothing else: key order, values and
	// types all still matter, so editing a date still fails. This was not a theoretical concern —
	// signing with json.MarshalIndent re-indented the embedded payload and produced a file that
	// failed to verify against its own signature.
	//
	// LIMIT, STATED SO NOBODY ASSUMES OTHERWISE: this forgives whitespace, NOT key reordering. A tool
	// that parses the payload and re-serialises it with sorted keys will invalidate the licence. Full
	// canonicalisation (RFC 8785) would fix that, and is deliberately not attempted here — it drags in
	// number formatting and unicode escaping rules that are easy to get subtly wrong, and a
	// canonicaliser that disagrees with the signer by one byte fails exactly like tampering. The
	// supported answer is not to rewrite the file; if it has been mangled, request a reissue.
	canonical, err := canonicalPayload(f.Payload)
	if err != nil {
		return nil, fmt.Errorf("%w: payload is not valid JSON: %v", ErrMalformed, err)
	}
	// Verified BEFORE unmarshalling into a Payload, so nothing inside an unverified document is ever
	// interpreted.
	if !ed25519.Verify(publicKey, canonical, sig) {
		return nil, ErrBadSignature
	}

	var p Payload
	if err := json.Unmarshal(f.Payload, &p); err != nil {
		return nil, fmt.Errorf("%w: payload is not a licence: %v", ErrMalformed, err)
	}
	if p.ExpiresAt.IsZero() {
		return nil, fmt.Errorf("%w: no expiry date", ErrMalformed)
	}
	return &p, nil
}

// canonicalPayload is the exact byte sequence a signature covers: the payload with insignificant
// whitespace removed. Both the signer and the verifier must use it, or they disagree.
func canonicalPayload(raw []byte) ([]byte, error) {
	var buf bytes.Buffer
	if err := json.Compact(&buf, raw); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// Sign produces a licence document for a payload.
//
// Exported so the signing CLI cannot drift from the verifier: there is one implementation of what
// gets signed, and both sides call it. The document is indented for readability, which is safe
// precisely because verification canonicalises.
func Sign(p Payload, priv ed25519.PrivateKey) ([]byte, error) {
	body, err := json.Marshal(p)
	if err != nil {
		return nil, err
	}
	canonical, err := canonicalPayload(body)
	if err != nil {
		return nil, err
	}
	doc, err := json.MarshalIndent(file{
		Payload:   canonical,
		Signature: base64.StdEncoding.EncodeToString(ed25519.Sign(priv, canonical)),
	}, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(doc, '\n'), nil
}

// State is what the rest of the system reads.
type State string

const (
	// StateTrial — no licence installed, still inside the trial window.
	StateTrial State = "trial"
	// StateValid — a verified licence, not expired.
	StateValid State = "valid"
	// StateExpiring — valid, but inside ExpiryWarningWindow. Same permissions as valid; exists so
	// the console can warn before anything stops working.
	StateExpiring State = "expiring"
	// StateExpired — trial or licence has run out. Control plane read-only.
	StateExpired State = "expired"
	// StateInvalid — a file is present but does not verify. Treated exactly like expired: no
	// control-plane writes, enforcement untouched.
	StateInvalid State = "invalid"
)

// ExpiryWarningWindow is how long before expiry the console starts warning. Two weeks is enough for
// a purchase order to clear at most organisations, which is the actual constraint.
const ExpiryWarningWindow = 14 * 24 * time.Hour

// TrialDuration is the free evaluation period, starting at first boot.
const TrialDuration = 30 * 24 * time.Hour

// Status is the full answer: state plus enough detail for the console and the health endpoint.
type Status struct {
	State State `json:"state"`
	// Licensed reports whether control-plane writes are permitted. Derived, not stored, so the
	// question is answered in exactly one place.
	Licensed bool `json:"licensed"`
	// Customer, ExpiresAt, Tier and Features are display detail. Populated for an expired licence
	// too, so the console can say what expired and when.
	Customer  string     `json:"customer,omitempty"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	Tier      string     `json:"tier,omitempty"`
	Features  []string   `json:"features,omitempty"`
	// DaysRemaining is negative once expired. Whole days, rounded down.
	DaysRemaining int `json:"daysRemaining"`
	// Reason explains a non-valid state in words the console can show verbatim.
	Reason string `json:"reason,omitempty"`
}

// Has reports whether a feature is enabled AND currently usable.
//
// A trial grants every in-scope feature: crippling an evaluation is how you lose it. An expired or
// invalid licence grants none — but note that this governs CONTROL-plane gating only. Enforcement of
// policies already created keeps working regardless; see gate.go.
func (s Status) Has(feature string) bool {
	if !s.Licensed {
		return false
	}
	// A trial grants every feature: crippling an evaluation is how you lose it.
	//
	// StateNotEnforced grants every feature too, and forgetting that was a production-breaking bug.
	// Every build except the on-premise one has no licence public key and so reports not_enforced with
	// an EMPTY feature list. Without this case, Has() answered false for ad, database and radius, and
	// the feature branch in Gate turned every feature-scoped path -- adminInvite, createDbHost,
	// DiscoverADPolicies and the rest -- into a 402 on our own SaaS and reference deployments the
	// moment licensing was wired in. The tests missed it because they asserted Licensed rather than
	// Has, and used StateValid where they should have used a non-enforcing build.
	if s.State == StateTrial || s.State == StateNotEnforced {
		return true
	}
	want := strings.ToLower(strings.TrimSpace(feature))
	for _, f := range s.Features {
		if strings.ToLower(strings.TrimSpace(f)) == want {
			return true
		}
	}
	return false
}

// Evaluate turns a verified licence, or the absence of one, into a Status.
//
// trialStart is the recorded first-boot time; the zero value means no trial has started yet, which
// is treated as starting now. now is a parameter rather than time.Now() so the state machine is
// testable without waiting a month.
func Evaluate(p *Payload, trialStart time.Time, now time.Time) Status {
	if p == nil {
		return evaluateTrial(trialStart, now)
	}

	expires := p.ExpiresAt
	remaining := expires.Sub(now)
	st := Status{
		Customer:      p.Customer,
		ExpiresAt:     &expires,
		Tier:          p.Tier,
		Features:      p.Features,
		DaysRemaining: int(remaining.Hours() / 24),
	}

	switch {
	case remaining <= 0:
		st.State, st.Licensed = StateExpired, false
		st.Reason = fmt.Sprintf("licence expired on %s", expires.UTC().Format("2 January 2006"))
	case remaining <= ExpiryWarningWindow:
		st.State, st.Licensed = StateExpiring, true
		st.Reason = fmt.Sprintf("licence expires on %s", expires.UTC().Format("2 January 2006"))
	default:
		st.State, st.Licensed = StateValid, true
	}
	return st
}

func evaluateTrial(trialStart, now time.Time) Status {
	if trialStart.IsZero() {
		trialStart = now
	}
	expires := trialStart.Add(TrialDuration)
	remaining := expires.Sub(now)
	st := Status{
		ExpiresAt:     &expires,
		DaysRemaining: int(remaining.Hours() / 24),
		Features:      []string{FeatureAD, FeatureDatabase, FeatureRADIUS},
	}
	if remaining <= 0 {
		st.State, st.Licensed = StateExpired, false
		st.Reason = "trial period has ended — install a licence to make further changes"
		return st
	}
	st.State, st.Licensed = StateTrial, true
	// NOTE FOR ANYONE BUILDING THE CONSOLE BANNER: a trial never reports StateExpiring. It is
	// StateTrial until the moment it is StateExpired, so a banner keyed on the state alone will show
	// nothing at all and then a read-only console. Warn on DaysRemaining instead -- it is populated
	// for the trial and for a purchased licence alike, so one rule covers both. Pinned by
	// TestTrialNeverReportsExpiring.
	st.Reason = fmt.Sprintf("trial: %s remaining", plural(st.DaysRemaining, "day"))
	return st
}

// plural renders a count with its unit, so a console does not show "1 days remaining".
func plural(n int, unit string) string {
	if n == 1 || n == -1 {
		return fmt.Sprintf("%d %s", n, unit)
	}
	return fmt.Sprintf("%d %ss", n, unit)
}

// EvaluateInvalid is the Status for a file that is present but does not verify.
//
// Separate from Evaluate because there is no payload to report and the reason must name what
// happened — a customer who edited a date needs to be told that, not shown "expired".
func EvaluateInvalid(err error) Status {
	reason := "licence file is not valid"
	switch {
	case errors.Is(err, ErrBadSignature):
		reason = "licence signature does not verify — the file has been modified, or was not issued by Authnull"
	case errors.Is(err, ErrMalformed):
		reason = "licence file is malformed"
	}
	return Status{State: StateInvalid, Licensed: false, Reason: reason}
}
